/**
 * Claude AI provider implementation using direct REST API fetch calls.
 */

export interface ClaudeConfig {
  apiKey: string;
  model?: string;
  maxTokens?: number;
}

/**
 * Generates content using Anthropic Claude API.
 * 
 * @param prompt The user prompt.
 * @param systemInstruction The system instructions/context.
 * @param config Configuration containing the apiKey, and optional model and maxTokens.
 * @returns The generated response string.
 */
export async function generateClaudeContent(
  prompt: string,
  systemInstruction: string,
  config: ClaudeConfig
): Promise<string> {
  const apiKey = config.apiKey;
  if (!apiKey) {
    throw new Error("Claude API key is not configured.");
  }

  const model = config.model || "claude-sonnet-4-6";
  const maxTokens = config.maxTokens || 4096;
  const url = "https://api.anthropic.com/v1/messages";

  const payload = {
    model,
    max_tokens: maxTokens,
    messages: [
      {
        role: "user",
        content: prompt,
      },
    ],
    system: systemInstruction,
  };

  try {
    const response = await fetch(url, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
        "anthropic-dangerous-direct-browser-access": "true",
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const errorText = await response.text();
      let errorMsg = `HTTP Error ${response.status}`;
      try {
        const errorJson = JSON.parse(errorText);
        if (errorJson.error?.message) {
          errorMsg = errorJson.error.message;
        }
      } catch {
        // use default errorMsg
      }
      throw new Error(`Claude API Error: ${errorMsg}`);
    }

    const data = await response.json();
    const textResult = data.content?.[0]?.text;
    if (!textResult) {
      throw new Error("No response content generated by Claude.");
    }

    return textResult;
  } catch (error: any) {
    throw error;
  }
}

export interface ClaudeVisionConfig {
  apiKey: string;
  model?: string;
  maxTokens?: number;
}

/**
 * Generates content using Anthropic Claude API with an image (multimodal).
 */
export async function generateClaudeVisionContent(
  prompt: string,
  systemInstruction: string,
  base64Data: string,
  mimeType: string,
  config: ClaudeVisionConfig
): Promise<string> {
  const apiKey = config.apiKey;
  if (!apiKey) {
    throw new Error("Claude API key is not configured.");
  }

  const model = config.model || "claude-sonnet-4-6";
  const maxTokens = config.maxTokens || 4096;
  const url = "https://api.anthropic.com/v1/messages";

  const payload = {
    model,
    max_tokens: maxTokens,
    messages: [
      {
        role: "user",
        content: [
          {
            type: "image",
            source: {
              type: "base64",
              media_type: mimeType,
              data: base64Data,
            },
          },
          {
            type: "text",
            text: prompt,
          },
        ],
      },
    ],
    system: systemInstruction,
  };

  try {
    const response = await fetch(url, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
        "anthropic-dangerous-direct-browser-access": "true",
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const errorText = await response.text();
      let errorMsg = `HTTP Error ${response.status}`;
      try {
        const errorJson = JSON.parse(errorText);
        if (errorJson.error?.message) {
          errorMsg = errorJson.error.message;
        }
      } catch {
        // use default errorMsg
      }
      throw new Error(`Claude API Error: ${errorMsg}`);
    }

    const data = await response.json();
    const textResult = data.content?.[0]?.text;
    if (!textResult) {
      throw new Error("No response content generated by Claude.");
    }

    return textResult;
  } catch (error: any) {
    throw error;
  }
}
