/**
 * Gemini AI provider implementation using direct REST API fetch calls.
 */

export interface GeminiConfig {
  apiKey: string;
  model?: string;
  temperature?: number;
}

/**
 * Generates content using Google Gemini API.
 * 
 * @param prompt The user prompt.
 * @param systemInstruction The system instructions/context.
 * @param config Configuration containing the apiKey, and optional model and temperature.
 * @returns The generated response string.
 */
export async function generateGeminiContent(
  prompt: string,
  systemInstruction: string,
  config: GeminiConfig
): Promise<string> {
  const apiKey = config.apiKey;
  if (!apiKey) {
    throw new Error("Gemini API key is not configured.");
  }

  const model = config.model || "gemini-3.1-flash-lite";
  const temperature = config.temperature ?? 0.2;
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

  const payload = {
    contents: [
      {
        parts: [
          {
            text: prompt,
          },
        ],
      },
    ],
    systemInstruction: {
      parts: [
        {
          text: systemInstruction,
        },
      ],
    },
    generationConfig: {
      temperature,
    },
  };

  try {
    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const errorText = await response.text();
      let errorMsg = `HTTP Error ${response.status}`;
      try {
        const errorJson = JSON.parse(errorText);
        if (errorJson.error?.message) {
          errorMsg = errorJson.error.message;
        }
      } catch {
        // use default errorMsg
      }
      throw new Error(`Gemini API Error: ${errorMsg}`);
    }

    const data = await response.json();
    const textResult = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!textResult) {
      throw new Error("No response content generated by Gemini.");
    }

    return textResult;
  } catch (error: any) {
    throw error;
  }
}
