/**
 * OpenAI AI provider implementation using direct REST API fetch calls.
 */

export interface OpenAIConfig {
  apiKey: string;
  model?: string;
  temperature?: number;
  responseType?: "json" | "text";
}

/**
 * Generates content using OpenAI API.
 * 
 * @param prompt The user prompt.
 * @param systemInstruction The system instructions/context.
 * @param config Configuration containing the apiKey, and optional model and temperature.
 * @returns The generated response string.
 */
export async function generateOpenAIContent(
  prompt: string,
  systemInstruction: string,
  config: OpenAIConfig
): Promise<string> {
  const apiKey = config.apiKey;
  if (!apiKey) {
    throw new Error("OpenAI API key is not configured.");
  }

  const model = config.model || "gpt-5.4-mini";
  const temperature = config.temperature ?? 0.7;
  const url = "https://api.openai.com/v1/chat/completions";

  const payload = {
    model,
    messages: [
      {
        role: "system",
        content: systemInstruction,
      },
      {
        role: "user",
        content: prompt,
      },
    ],
    temperature,
    ...(config.responseType === "json" && { response_format: { type: "json_object" } }),
  };

  try {
    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const errorText = await response.text();
      let errorMsg = `HTTP Error ${response.status}`;
      try {
        const errorJson = JSON.parse(errorText);
        if (errorJson.error?.message) {
          errorMsg = errorJson.error.message;
        }
      } catch {
        // use default errorMsg
      }
      throw new Error(`OpenAI API Error: ${errorMsg}`);
    }

    const data = await response.json();
    const textResult = data.choices?.[0]?.message?.content;

    if (!textResult) {
      throw new Error("No response content generated by OpenAI.");
    }

    return textResult;
  } catch (error: any) {
    throw error;
  }
}

export interface OpenAIVisionConfig {
  apiKey: string;
  model?: string;
  temperature?: number;
}

/**
 * Generates content using OpenAI API with an image (multimodal).
 */
export async function generateOpenAIVisionContent(
  prompt: string,
  systemInstruction: string,
  base64Data: string,
  mimeType: string,
  config: OpenAIVisionConfig
): Promise<string> {
  const apiKey = config.apiKey;
  if (!apiKey) {
    throw new Error("OpenAI API key is not configured.");
  }

  const model = config.model || "gpt-5.4-mini";
  const temperature = config.temperature ?? 0.1;
  const url = "https://api.openai.com/v1/chat/completions";

  const payload = {
    model,
    messages: [
      {
        role: "system",
        content: systemInstruction,
      },
      {
        role: "user",
        content: [
          {
            type: "text",
            text: prompt,
          },
          {
            type: "image_url",
            image_url: {
              url: `data:${mimeType};base64,${base64Data}`,
            },
          },
        ],
      },
    ],
    temperature,
  };

  try {
    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const errorText = await response.text();
      let errorMsg = `HTTP Error ${response.status}`;
      try {
        const errorJson = JSON.parse(errorText);
        if (errorJson.error?.message) {
          errorMsg = errorJson.error.message;
        }
      } catch {
        // use default errorMsg
      }
      throw new Error(`OpenAI API Error: ${errorMsg}`);
    }

    const data = await response.json();
    const textResult = data.choices?.[0]?.message?.content;

    if (!textResult) {
      throw new Error("No response content generated by OpenAI.");
    }

    return textResult;
  } catch (error: any) {
    throw error;
  }
}
